{"uuid": "46b1ca6b-5a31-4876-9448-517a76526d72", "children": ["db3c1fe1-ba79-4f8f-864c-2bbca56a502f"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\ПК\\Sprint_4\\test\\conftest.py\", line 6, in driver\n    driver = webdriver.Firefox()\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 59, in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 41, in get_path\n    raise NoSuchDriverException(msg) from err\n"}, "start": 1693790402084, "stop": 1693790403056}], "start": 1693790402084, "stop": 1693790403103}