{"uuid": "69bd8851-fae2-4f46-9b00-d797f69621a0", "children": ["fb523ef5-78ec-447f-99f2-9c23fb7b1b23"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\ПК\\Sprint_4\\test\\conftest.py\", line 6, in driver\n    driver = webdriver.Firefox()\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 59, in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 41, in get_path\n    raise NoSuchDriverException(msg) from err\n"}, "start": 1693790400249, "stop": 1693790401621}], "start": 1693790400249, "stop": 1693790402084}