{"uuid": "4bfeaa52-342c-40b7-8173-0d91f3597f91", "children": ["9db3e18a-ac52-488c-a956-7f11d5df93ec"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\ПК\\Sprint_4\\test\\conftest.py\", line 6, in driver\n    driver = webdriver.Firefox()\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 59, in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n  File \"C:\\Users\\ПК\\Sprint_4\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 41, in get_path\n    raise NoSuchDriverException(msg) from err\n"}, "start": 1693790408431, "stop": 1693790409455}], "start": 1693790408431, "stop": 1693790409516}